spring.application.name: dynamoservice

aws:
  accesskey: DUMMYIDEXAMPLE
  dynamodb:
    endpoint: http://localhost:8000/
  region: ""
  secretkey: DUMMYEXAMPLEKEY

spring:
  profiles:
    active: development
