spring.application.name: dynamoservice

amazon:
  aws:
    accesskey: DUMMYIDEXAMPLE
    secretkey: DUMMYEXAMPLEKEY
  dynamodb:
    endpoint: http://localhost:8000/

spring:
  profiles:
    active: development
