package com.wahlen.dynamoservice.persistence.model

import com.amazonaws.services.dynamodbv2.datamodeling.*
import com.wahlen.dynamoservice.configuration.DynamoDBConfiguration
import java.time.LocalDateTime
import java.time.LocalDateTime.now

@DynamoDBTable(tableName = "ProductInfo")
data class ProductInfo(
    @field:DynamoDBHashKey
    @field:DynamoDBAutoGeneratedKey
    var id: String? = null,

    @field:DynamoDBAttribute
    @field:DynamoDBIndexHashKey(globalSecondaryIndexName = "productInfo_name_created_at_idx")
    var name: String = "",

    @field:DynamoDBAttribute
    var msrp: String = "",

    @field:DynamoDBAttribute
    var cost: String = "",

    @field:DynamoDBAttribute
    @field:DynamoDBTypeConverted(converter = DynamoDBConfiguration.Companion.LocalDateTimeConverter::class)
    @field:DynamoDBIndexRangeKey(globalSecondaryIndexName = "productInfo_name_created_at_idx")
    var createdAt: LocalDateTime = now()
) {
    companion object {
        fun create(name: String, msrp: String, cost: String): ProductInfo =
            ProductInfo(name = name, msrp = msrp, cost = cost)
    }
}
