package com.wahlen.dynamoservice.persistence.model

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "ProductInfo")
class ProductInfo {
    @get:DynamoDBAutoGeneratedKey
    @get:DynamoDBHashKey
    var id: String? = null

    @get:DynamoDBAttribute
    var msrp: String? = null

    @get:DynamoDBAttribute
    var cost: String? = null

    constructor()

    constructor(cost: String?, msrp: String?) {
        this.msrp = msrp
        this.cost = cost
    }
}
